#!/usr/bin/env bash
# Runs on user login

startx=false
if which startx > /dev/null 2>&1
then
	case "$( tty )" in
	(/dev/tty*)
		printf 'Start X? (y/n): ' 1>&2
		read reply || echo n 1>&2
		case "$reply" in
		([Yy]*) startx=true ;;
		esac
		;;
	esac
fi

####### EXPORTS ###########
export EDITOR="nvim"
export EDITOR_GUI="leafpad"
export TERMINAL="alacritty_rainbow"
export PAGER="less"
export READER="zathura"
export WEB_BROWSER="firefox"
export IDE_GUI="code"
# export LOCKSCREEN="lock-glitch"
export LOCKSCREEN="lock-better"
export FILE="vifmuber"
export FILE_GUI="thunar"
export SUDO_ASKPASS=$HOME/.custombin/rofi-askpass # GUI for passwd prompt.. change with rofi pass?

export XDG_CONFIG_HOME="$HOME/.config"
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
#export XDG_CURRENT_DESKTOP=XFCE
#export XDG_CONFIG_DIRS=/etc/xdg

export SSH_KEY_PATH="~/.ssh/rsa_id" # ssh
export LANG=en_US.UTF-8             # You may need to manually set your language environment
export MANPATH="$MANPATH:/usr/local/man"
export ZIM_HOME=${HOME}/arch-dotfiles/shell/zimfw # Default zim location
# export ARCHFLAGS="-arch x86_64"   # Compilation flags

# Adds `~/.local/bin/` and all subdirectories to $PATH
export PATH="$PATH:$(du "$HOME/.custombin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"

# Need to understand this..
#typeset -gU cdpath fpath mailpath path

#if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  #exec startx
#fi
# if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
#   startx
# fi

# Rewrite question prompt
# Hand off to X if requested
"$startx" && exec startx

[ -f ~/.alias_fn ] && source $HOME/.alias_fn  # Set aliases and functions