#!/usr/bin/env bash

####### EXPORTS ###########
export EDITOR="nvim"
export EDITOR_GUI="leafpad"
export TERMINAL="alacritty"
export PAGER="less"
export READER="zathura"
export WEB_BROWSER="firefox"
export IDE_GUI="code"
# export LOCKSCREEN="lock-glitch"
export LOCKSCREEN="lock-better"
export FILE="vifmuber"
export FILE_GUI="pcmanfm"
export SUDO_ASKPASS=$HOME/.scripts/rofi-askpass # GUI for passwd prompt.. change with rofi pass?
export SCREENSHOT="flameshot gui"

export XDG_CONFIG_HOME="$HOME/.config"
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
#export XDG_CURRENT_DESKTOP=XFCE
#export XDG_CONFIG_DIRS=/etc/xdg

export SSH_KEY_PATH="~/.ssh/rsa_id" # ssh
export LANG=en_US.UTF-8             # You may need to manually set your language environment
export MANPATH="$MANPATH:/usr/local/man"
export ZIM_HOME=${HOME}/arch-dotfiles/shell/zimfw # Default zim location
# export ARCHFLAGS="-arch x86_64"   # Compilation flags

export PATH="$PATH:\
$HOME/.local/bin:\
$HOME/.scripts:\
/usr/local/bin:\
/bin"

# Need to understand this..
#typeset -gU cdpath fpath mailpath path

#if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  #exec startx
#fi

