#!/bin/sh

export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
dbus-daemon --session &
eval $(ssh-agent -s)
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# ToDo: Research and potentially apply
# setxkbmap -model "evdev" -rules "evdev" \
#   -layout "us,pt" -variant "altgr-intl,sundeadkeys" \
#   -option "grp:alt_shift_toggle" -option caps:swapescape -option terminate:ctrl_alt_bksp

##########################################
#xmodmap -e "keycode 108 = Super_L"  # reassign Alt_R to Super_L
#xmodmap -e "remove mod1 = Super_L"  # make sure X keeps it out of the mod1 group

exec bspwm
