#!/bin/sh
export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0

# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto

dbus-daemon --session &
start-pulseaudio-x11

eval $(ssh-agent -s)
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# if [ "$(cat /etc/hostname)" = "atreides" ]; then
  # xrandr --output HDMI-A-0 --primary --auto --left-of DVI-I-1
# fi

# setxkbmap -model "evdev" -rules "evdev" \
#   -layout "us,pt" -variant "altgr-intl,sundeadkeys" \
#   -option "grp:alt_shift_toggle" -option caps:swapescape -option terminate:ctrl_alt_bksp

#exec qtile
#exec dwm
#pgrep sxhkd >/dev/null || sxhkd & # Start hotkey daemon
setbg                                       # Set background
pgrep sxhkd >/dev/null || sxhkd &           # Hotkey Daemon
pgrep mpd >/dev/null || mpd &               # Music Server Daemon
pgrep clipit >/dev/null || clipit -dn &     # Clipboard manager
prgrep compton >/dev/null || compton &      # X compositor
xset b off                                  # Turn off system beep
unclutter -b                                # Auto-hide inactive cursor
nm-applet &                                 # Network Manager applet
xset r rate 230 35                          # Key repeat threshold and speed
wmname LG3D                                 # This fixes many java apps, don't fuck with it.

# Give priv for non-network local connects to ACL, bypassing the dumbass python xlib
# that is refusing to establish a connection to local X serv on behalf of ueberzug(vifm)
xhost +local:

exec dwm-init
