#!/usr/bin/env sh

sxhkd &     # Keybind daemon
compton -b &    # X Compositor
setbg &     # Set background image
# Find monitor names with xrandr -q
xrandr -q | grep '^[a-zA-Z0-9]* connected' | awk '{ print $1 }' | while read -r line ; do
  #echo $line
  bspc monitor $line -d 1 2 3 4 5 6 7 8 9 0
done

lemonbar-run &    # Ensure this script is located in $PATH
xsetroot -cursor_name left_ptr    # Sets a default cursor
#bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
bspc config pointer_modifier mod4   # Super key for mouse actions
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config split_ratio          0.50
bspc config border_width    1
bspc config border_radius   10
bspc config window_gap      14

bspc config borderless_monocle   true
bspc config gapless_monocle      true 


bspc rule -a Musixmatch  state=floating