#!/usr/bin/env sh
# Runs only if no previous instance exists
run_one_only(){
  pgrep $1 >/dev/null || "$@" &
}
#### AUTOSTART ####
sxhkd &         # Keybind daemon
run_one_only dunst
run_one_only start-pulseaudio-x11
run_one_only mpd
run_one_only clipit
run_one_only unclutter -b
run_one_only nm-applet
#pgrep sxhkd >/dev/null || sxhkd &         # Keybind daemon
#pgrep dunst >/dev/null || dunst &         # Notification daemon
#start-pulseaudio-x11
#pgrep mpd >/dev/null || mpd &               # Music Server Daemon
# pgrep clipit >/dev/null || clipit -dn &     # Clipboard manager
# pgrep unclutter >/dev/null || unclutter -b  # Auto-hide inactive cursor
# pgrep nm-applet >/dev/null || nm-applet &   # Network Manager applet
xset b off                                  # Turn off fucking BOOP
xset r rate 230 35                          # Key repeat threshold and speed
# Give priv for non-network local connects to ACL, bypassing the dumbass python xlib
# that is refusing to establish a connection to local X serv on behalf of ueberzug(vifm)
xhost +local:
export _JAVA_AWT_WM_NONREPARENTING=1  # Make Java apps work
#wmname LG3D                           # Makes java apps behave correctly

handle_monitors(){
  autorandr -c   # Load saved xrandr configuration (Monitor layouts)
  nitrogen --restore   # Set background image
  run_one_only lemonbar-run   # Ensure this script is located in $PATH
  run_one_only tint2
  run_one_only compton       # X compositor
  xrandr -q | grep '^[a-zA-Z0-9]* connected' | awk '{ print $1 }' | while read -r line ; do
    bspc monitor $line -d 1 2 3 4 5 6 7 8 9 0
  done
}

handle_monitors &


#### MONITOR CONFIG ####
# Find monitor names with xrandr -q
# bspc monitor DisplayPort-0 -d 1 2 3
# bspc monitor DisplayPort-1 -d 4 5 6
# bspc monitor HDMI-A-0 -d 7 8 9 
# bspc monitor eDP1 -d I II III IV V VI VII VIII IX X


#### BSPWM configuration ####
#bspc config border_radius       8    # Needs custom build of bspwm to support this
bspc config border_width         3
bspc config window_gap           10
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
xsetroot -cursor_name left_ptr    # Sets a default cursor

#### BSPWM COLORING ####
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

#### APP RULES ####
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

