#!/usr/bin/env bash
# Author: Danijel Milosevic

file=/usr/share/X11/xkb/rules/base.lst
#sed -n '/! layout/,$p' $file > output.txt
#sed '/! variant/,$d' $file > output.txt

#sed -n '/! layout/,$p' $file | sed '/! variant/,$d' > output.txt


#awk '/Mem:/ { print $2 } /buffers\/cache/ { print $3 }'
sed -n '/! layout/,$p' $file | sed '/! variant/,$d' \
| awk '{ print $0 }'
